# Generated by Django 3.2.7 on 2021-09-11 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TF_IDF', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filesdsd',
        ),
        migrations.AddField(
            model_name='files',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='words',
            name='file',
            field=models.ForeignKey(db_column='file', null=True, on_delete=django.db.models.deletion.PROTECT, to='TF_IDF.files'),
        ),
    ]
