# Generated by Django 3.2.7 on 2021-09-11 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TF_IDF', '0002_auto_20210911_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file',
        ),
    ]
