# Generated by Django 3.1.6 on 2021-09-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TF_IDF', '0008_auto_20210912_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='idf',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
