# Generated by Django 3.2.7 on 2021-09-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TF_IDF', '0009_words_idf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(null=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='words',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
